---
title: "Education"
page-layout: full
toc-expand: false
sidebar: empty-sidebar-on-other-pages
---

## Massive Open Online Courses (MOOCs)
### [Data Science in Earth and Environmental Sciences](https://edx.hydrolearn.org/courses/course-v1:SyracuseUniversity+EAR601+2020_Fall/about){target="_blank"}
*	This course is designed to introduce learners to the basics of R and Python programming as well as the application of emerging data analytics and machine learning methods in the Earth and Environmental Sciences.

### [Environmental Issues Related to Brine Disposal from Oil and Gas Development in Pennsylvania](https://serc.carleton.edu/hydromodules/units/191769.html){target="_blank"}
*	In this course, students will explore three aspects of oil and gas development related production waters: 1) why the waters cannot be discharged directly into rivers; 2) how disposal can be sometimes associated with earthquakes; 3) how Pennsylvania tries to find ways to dispose of brines safely. We use different online services to find publicly available data.


## Syracuse University
### EAR 600 – Foundations of Geosciences: Fall 2022
*	This course is intended to give students from across the geosciences the opportunity to explore and discuss some of the more exciting discoveries, mysteries, and theories underpinning different aspects of the Earth system and to exchange ideas with people from across the different subdisciplines of our department.

### EAR 419/601 – Aqueous Geochemistry: Fall 2022
*	This course covers topics including processes and evolution of the chemical composition of water in the natural hydrologic cycle as well as methods of hydrochemical interpretation applied to ground water and pollution problems. This course includes lectures, field work, and laboratory work.

### EAR 200 – Introduction to Data Analysis in Earth Sciences: Spring 2022
*	This course covers topics including describing and comparing sample populations, simple data manipulations, data visualization, creating and working with databases, surface contouring and modeling, basic GIS principles, and simple computer modeling of geologic processes.

### EAR 205 – Water and Our Environment: Every Spring
*	This course covers the origin, occurrence, chemistry, and hydrology of water on earth. Class topics include climate change, contamination, and water supply issues within context of water sustainability.

### EAR 401/601 – Hydrogeology: Fall 2020
* Elements of the hydrologic cycle, properties of aquifers, principles of groundwater flow, groundwater flow to wells, regional groundwater flow, basic water chemistry and groundwater contamination, and field methods and groundwater modeling


## Pennsylvania State University
### GEOSC/GEOG 497 – Data Mining in Environmental Sciences: Fall 2019
*	Applied both conventional and emerging data analytics tools to address real-world environmental science problems through mini-lectures and hands-on projects

### GEOSC 560 – Kinetics of Geological Processes (Interim Instructor): Spring 2017 and Spring 2019
* Basics of isotope geochemistry
* Applied Data-driven models to assess the impact of natural and anthropogenic features on weathering rate on a watershed scale

## University of Michigan
### EARTH 477 – Hydrogeology: 2013 – 2016
* Guided 50+ students to understand the fate and transport of contaminants from Underground Storage Tanks via hands-on hydrogeological lab work and the interpretation of stratigraphic information

### EARTH 408 – Introduction to GIS in the Earth Sciences: Fall 2016
* Implemented 2D & 3D spatial analysis in ArcGIS; received positive teaching evaluation (rated at 4.5-5.0 out of 5.0) from students.


## Extracurricular Teaching
### [Shale Network Workshop](http://www.shalenetwork.org/content/2018-shale-network-workshop){target="_blank"} at Penn State University: May 2018
* Co-led the computer module demonstration and hands-on exercise covering water chemistry about Marcellus-related spills for over 40 participants
