---
title: "Join Us"
page-layout: full
sidebar: false
title-block-banner: true
---

## Graduate Students

Students interested in graduate study are encouraged to contact [Prof. Wen](/contact.qmd){target="_blank"} before applying. Please include a CV, a brief description of any prior research activities (prior research experience is not required for admission), and your current research and educational interests. Interested students should also review the **[departmental application information](https://artsandsciences.syracuse.edu/earth-sciences-department/graduate-programs-earth-sciences/application-information/){target="_blank"}**.

I am currently seeking applicants for graduate student positions interested in three tracks:

**Noble gas geochemistry track**: Students will apply noble gases as a dating and tracing tool for fluid and solid samples. Students will be trained in noble gas geochemistry with respect to both laboratory and data analysis skills. Students will conduct experimental noble gas work in shallow and deep groundwater, natural gas, and/or rock samples.

**Environmental data sciences and geospatial modeling track**: Students will work on a DOE-funded project to learn and apply machine learning and geospatial modeling to analyze multidisciplinary datasets to assess environmental impacts and greenhouse gas emission of oil and gas wells.

**Global elemental and water cycles track**: Students will assess the elemental and water fluxes from the land water systems using machine learning, hydrological modeling, and/or Earth system modeling. Interested students should have a background in hydrogeology, geochemistry, or relevant fields and a motivation to learn programming.

**External Graduate Student Fellowships** I am happy to work with interested candidates to collaboratively develop proposals for external graduate student fellowships, e.g., [NSF GRFP](https://www.nsfgrfp.org){target="_blank"}.

## Undergraduate Students

Students interested in conducting research in the WEN Research Group should contact Prof. Wen. Helpful context includes your major, expected graduation year, relevant coursework, and the research questions or skills you hope to explore.

## Postdoctorals and Others

**External Postdoctoral Fellowships** I am happy to work with interested candidates to collaboratively develop proposals for external postdoctoral fellowships, e.g., [NSF EAR-PF](https://new.nsf.gov/funding/opportunities/ear-postdoctoral-fellowships-ear-pf){target="_blank"}. Prospective collaborators and visiting scholars are also welcome to reach out with a concise description of shared research or teaching interests.
