---
title: "Publication"
page-layout: full
sidebar: false
---

You can find my publications on my [Google Scholar](https://scholar.google.com/citations?user=5jsj4tUAAAAJ){target="_blank"} webpage.

## Journal Articles
† = Student author, directly supervised by Wen at time of publication

†† = Student author of collaborator at time of publication

### 2024
* Hammond, P.A., **Wen, T.**, Woda, J. and Oakley, D., 2024. Pathways and environmental impacts of methane migration: case studies in the Marcellus Shale, USA. _Geofluids_. [[download pdf]](/files/papers/Hammond_2024_Geofluids.pdf){target="_blank"}

* Liu, Y., Wang, T., **Wen, T.**, Zhang, J., Liu, B., Li, Y., Zhang, H., Rong, X., Ma, L., Guo, F., Liu, X and Sun, Y., 2024. Deep learning-based grain size decomposition model: A feasible solution for dealing with methodological uncertainty. _Sedimentology_. [[download pdf]](/files/papers/Liu_2024_Sedimentology.pdf){target="_blank"}

* †Nesheim, S., Yu, Z., Tuttle, S., †Klein, J. and **Wen, T.**, 2024. Assessing impacts of cemeteries on water quality in an urban headwater watershed with mixed human-built infrastructure. _Hydrological Processes_. [[download pdf]](/files/papers/Nesheim_2024_HP.pdf){target="_blank"}

### 2023
* Kang, M., Boutot, J., McVay, R.C., Roberts, K., Jasechko, S., Perrone, D., **Wen, T.**, Lackey, G., Raimi, D., Digiulio D.C., Shonkoff, S.B., Carey, J.W., Elliott, E.G., Vorhees, D.J. and Peltz, A., 2023. Environmental risks and opportunities of orphaned oil and gas wells in the United States. _Environmental Research Letters_. [[download pdf]](/files/papers/Kang_2023_ERL.pdf){target="_blank"}

* ††Shaughnessy, A.R., ††Forgeng, M.J., **Wen, T.**, Gu, X., Hemingway, J. and Brantley, S.L., Linking Stream Chemistry to Subsurface Redox Architecture. _Water Resources Research_. [[download pdf]](/files/papers/Shaughnessy_2023_WRR.pdf){target="_blank"}

* †E, B., Zhang, S., Driscoll, C.T. and **Wen, T.**, Human and natural impacts on the U.S. freshwater salinization and alkalinization: A machine learning approach. _Science of The Total Environment_. [[download pdf]](/files/papers/E_2023_STOTEN.pdf){target="_blank"}

* Carter, E., Hultquist, C. and **Wen, T.**, 2023. GRRIEn analysis: a data science cheat sheet for earth scientists learning from global earth observations. _Artificial Intelligence for the Earth Systems_. [[download pdf]](/files/papers/Carter_2023_AIES.pdf){target="_blank"}

### 2022
* Cheng, P., Xiao, X., Ren, B., **Wen, T.** and Yu, S., 2022. Editorial: New advances in light oil/condensate geochemistry. _Frontiers in Earth Science_. [[download pdf]](/files/papers/Cheng_2022_FIES.pdf){target="_blank"}

* †Epuna, F., ††Shaheen, S. and **Wen, T.**, 2022. Road Salting and Natural Brine Migration Revealed as Major Sources of Groundwater Contamination Across Regions of Northern Appalachia With and Without Unconventional Oil and Gas Development. _Water Research_. [[download pdf]](/files/papers/Epuna_et_al_2022_WR.pdf){target="_blank"}

* **Wen, T.**, ††Chen, C., Zheng, G., Bandstra, J. and Brantley, S.L., 2022. Using a Neural Network – Physics-based Hybrid Model to Predict Soil Reaction Fronts. _Computers & Geosciences_. [[download pdf]](/files/papers/Wen_2022_CG.pdf){target="_blank"}

* ††Wang, S., Huang, X., **Wen, T.**, Wang, X., Wang, H., Han, Y., Li, Z., Kuang, J. and Qi S., 2022. Noble Gases in Shallow Aquifers Preserve Signatures of Boiling Events beneath Weishan Volcano of Wudalianchi Volcanic Field, Northeast China. _Journal of Hydrology_. [[download pdf]](/files/papers/Wang_2022_JH.pdf){target="_blank"}

* ††Shaheen, S.W., **Wen, T.**, Herman, A., Brantley, S.L., 2022. Geochemical Evidence of Potential Groundwater Contamination with Human Health Risks Where Hydraulic Fracturing Overlaps with Extensive Legacy Hydrocarbon Extraction. _Environmental Science & Technology_. [[download pdf]](/files/papers/Shaheen_2022_EST.pdf){target="_blank"}

* Boumaiza, L., Walter, J., Chesnaux, R., Stotler, R., **Wen, T.**, Johannesson K., Brindha K. and Huneau, F., 2022. Chloride-salinity as indicator of the chemical composition of groundwater: empirical predictive model based on aquifers in Southern Quebec, Canada. _Environmental Science and Pollution Research_. [[download pdf]](/files/papers/Boumaiza_2022_ESPR.pdf){target="_blank"}

* He, Y., Zhou, Y., **Wen, T.**, Zhang, S., Huang, F., Zou, X., Ma, X., Zhu, Y., 2022. A review of machine learning in geochemistry and cosmochemistry: Method improvements and applications. _Applied Geochemistry_. [[download pdf]](/files/papers/He_2022_Applied_Geochemistry.pdf){target="_blank"}

### 2021
* Brantley, S.L., **Wen, T.**, Agarwal, D., Catalano, J.G., Schroeder, P.A., Lehnert, K., Varadharajan, C., Pett-Ridge, J., Engle, M., Castronova, A.M., Hooper, R.P., Ma, X., Jin, L., McHenry, K., Aronson, E., Shaughnessy, A.R., Derry, L.A., Richardson, J., Bales, J., Pierce, E.M., 2021. The future low-temperature geochemical data-scape as envisioned by the U.S. geochemical community. _Computers & Geosciences_. [[download pdf]](/files/papers/Brantley_2021_CG.pdf){target="_blank"}

* Liu, R., **Wen, T.**, Amalberti, J., Zheng, J., Hao, F. and Jiang D., 2021. The Dichotomy in Noble Gas Signatures Linked to Tectonic Deformation in Wufeng-Longmaxi Shale, Sichuan Basin. _Chemical Geology_. [[download pdf]](/files/papers/Liu_2021_Chemical_Geology.pdf){target="_blank"}

* Zheng, G., Liu, C., Wei, H., Jenkins, P., Chen, C., **Wen, T.** and Li, Z., 2021. Knowledge-based Residual Learning. In _Proceedings of the 30th International Joint Conference on Artificial Intelligence_ (IJCAI 2021). [[download pdf]](/files/papers/Zheng_2021_IJCAI.pdf){target="_blank"}

* ††Shaughnessy, A., Gu, X., **Wen, T.** and Brantley, S.L., 2021. Machine Learning Deciphers CO2 Sequestration and Subsurface Flowpaths from Stream Chemistry. _Hydrology and Earth System Sciences_. [[download pdf]](/files/papers/Shaughnessy_2021_HESS.pdf){target="_blank"}

* **Wen, T.**, Liu, M., Woda, J., Zheng, G. and Brantley, S.L., 2021. Detecting anomalous methane in groundwater within hydrocarbon production areas across the United States. _Water Research_. [[download pdf]](/files/papers/Wen_2021_WR.pdf){target="_blank"}

* Niu, X., **Wen, T.** and Brantley, S.L., 2021. Exploring the trend of stream sulfate concentrations as U.S. power plants shift from coal to shale gas. _Environmental Pollution_. [[download pdf]](/files/papers/Niu_2021_Environmental_Pollution.pdf){target="_blank"}

### Prior to 2021
* ††Agarwal, A., **Wen, T.**, ††Chen, A., ††Zhang, A.Y., Niu, X., Zhan, X., Xue, L., Brantley, S.L., 2020. Assessing Contamination of Stream Networks Near Shale Gas Development Using a New Geospatial Tool. _Environmental Science & Technology_. [[download pdf]](/files/papers/Agarwal_Wen_2020_EST.pdf){target="_blank"}

* ††Woda, J., **Wen, T.**, Lemon, J., ††Marcon, V., Keeports, C.M., Zelt, F., Steffy, L.Y. and Brantley, S.L., 2020. Methane concentrations in streams reveal gas leak discharges in regions of oil, gas, and coal development. _Science of The Total Environment_. [[download pdf]](/files/papers/Woda_2020_STOTEN.pdf){target="_blank"}

* Hammond, P.A., **Wen, T.**, Brantley, S.L. and Engelder, T., 2020. Gas well integrity and methane migration: evaluation of published evidence during shale-gas development in the USA. _Hydrogeology Journal_. [[download pdf]](/files/papers/Hammond_2020_Hydrogeology.pdf){target="_blank"}

* ††Shaughnessy, A., **Wen, T.**, Niu, X. and Brantley, S.L., 2019. Three Principles to Use in Streamlining Water Quality Research through Data Uniformity. _Environmental Science & Technology_. [[download pdf]](/files/papers/Shaughnessy_2019_EST.pdf){target="_blank"}

* **Wen, T.**, ††Woda, J., ††Marcon, V., Niu, X., Li, Z. and Brantley, S.L., 2019. Exploring How to Use Groundwater Chemistry to Identify Migration of Methane near Shale Gas Wells in the Appalachian Basin. _Environmental Science & Technology_. [[download pdf]](/files/papers/Wen_2019_EST.pdf){target="_blank"}

* Liu, R., Heinemann, N., Liu, J., Zhu, W., Wilkinson, M., Xie, Y., Wang, Z., **Wen, T.**, Hao, F., Haszeldine, S.R., 2019. CO2 Sequestration by Mineral Trapping in Natural Analogues in the Yinggehai Basin, South China Sea. _Marine and Petroleum Geology_. [[download pdf]](/files/papers/Liu_2019_MPG.pdf){target="_blank"}

* **Wen, T.**, ††Agarwal, A., Xue, L., ††Chen, A., Herman, A., Li, Z. and Brantley, S.L., 2019. Assessing Changes in Groundwater Chemistry in Landscapes with More than 100 Years of Oil and Gas Development. _Environmental Science: Processes & Impacts_. [[download pdf]](/files/papers/Wen_2019_ESPI.pdf){target="_blank"}

* ††Woda, J., **Wen, T.**, ††Oakley, D., Yoxtheimer, D., Engelder, T., Castro, M.C. and Brantley, S.L., 2018. Detecting and Explaining Why Aquifers Occasionally Become Degraded Near Hydraulically Fractured Shale Gas Wells. _Proceedings of the National Academy of Sciences_. [[download pdf]](/files/papers/Woda_2018_PNAS.pdf){target="_blank"}

* Larson, T.E., Nicot, J.P., Mickler, P., Castro, M.C., Darvari, R., **Wen, T.** and Hall, C.M., 2018. Monitoring Stray Natural Gas in Groundwater with Dissolved Nitrogen. An Example from Parker County, Texas. _Water Resources Research_. [[download pdf]](/files/papers/Larson_2018_WRR.pdf){target="_blank"}

* **Wen, T.**, Niu, X., Gonzales, M., ††Zheng, G., Li, Z. and Brantley, S.L., 2018. Big groundwater data sets reveal possible rare contamination amid otherwise improved water quality for some analytes in a region of Marcellus Shale development. _Environmental Science & Technology_. [[download pdf]](/files/papers/Wen_2018_EST.pdf){target="_blank"}

* Niu, X., **Wen, T.**, Li, Z. and Brantley, S.L., 2018. One Step toward Developing Knowledge from Numbers in Regional Analysis of Water Quality. _Environmental Science & Technology_. [[download pdf]](/files/papers/Niu_2018_EST.pdf){target="_blank"}

* **Wen, T.**, Pinti, D.L., Castro, M.C., López-Hernández, A., Hall, C.M., Shouakar-Stash, O. and Sandoval-Medina, F., 2018. A Noble Gas and <sup>87</sup>Sr/<sup>86</sup>Sr Study in Fluids of the Los Azufres Geothermal Field, Mexico – Assessing Impact of Exploitation and Constraining Heat Sources. _Chemical Geology_. [[download pdf]](/files/papers/Wen_2018_Chemical_Geology.pdf){target="_blank"}

* Brantley, S.L., Vidic, R.D., Brasier, K., Yoxtheimer, D., Pollak, J., Wilderman, C. and **Wen, T.**, 2018. Engaging over data on fracking and water quality. _Science_. [[download pdf]](/files/papers/Brantley_2018_Science.pdf){target="_blank"}

* **Wen, T.**, Castro, M.C., Nicot, J.P., Hall, C.M., Pinti, D.L., Mickler, P., Darvari, R. and Larson, T., 2017. Characterizing the noble gas isotopic composition of the Barnett Shale and Strawn group and constraining the source of stray gas in the Trinity Aquifer, north-central Texas. _Environmental Science & Technology_. [[download pdf]](/files/papers/Wen_2017_EST.pdf){target="_blank"}

* **Wen, T.**, Castro, M.C., Nicot, J.P., Hall, C.M., Larson, T., Mickler, P. and Darvari, R., 2016. Methane Sources and Migration Mechanisms in Shallow Groundwaters in Parker and Hood Counties, Texas - A Heavy Noble Gas Analysis. _Environmental Science & Technology_. [[download pdf]](/files/papers/Wen_2016_EST.pdf){target="_blank"}

* **Wen, T.**, Castro, M.C., Ellis, B.R., Hall, C.M. and Lohmann, K.C., 2015. Assessing compositional variability and migration of natural gas in the Antrim Shale in the Michigan Basin using noble gas geochemistry. _Chemical Geology_. [[download pdf]](/files/papers/Wen_2015_Chemical_Geology.pdf){target="_blank"}

* **Wen, T.**, Castro, M.C., Hall, C.M., Pinti, D.L. and Lohmann, K.C., 2015. Constraining groundwater flow in the Glacial Drift and Saginaw aquifers in the Michigan Basin through helium concentrations and isotopic ratios. _Geofluids_. [[download pdf]](/files/papers/Wen_2015_Geofluids.pdf){target="_blank"}

* Boucher, C., Pinti, D.L., Roy, M., Castro, M.C., Cloutier, V., Blanchette, D., Larocque, M., Hall, C.M., **Wen, T.** and Sano, Y., 2015. Groundwater age investigation of eskers in the Amos region, Quebec, Canada. _Journal of Hydrology_. [[download pdf]](/files/papers/Boucher_2015_Journal_of_Hydrology.pdf){target="_blank"}

* Nie, Y., Liu, X., **Wen, T.**, Sun, L. and Emslie, S.D., 2014. Environmental implication of nitrogen isotopic composition in ornithogenic sediments from the Ross Sea region, East Antarctica: Δ<sup>15</sup>N as a new proxy for avian influence. _Chemical Geology_. [[download pdf]](/files/papers/Nie_2014_Chemical_Geology.pdf){target="_blank"}

## Chapters in Books

* **Wen, T.**, 2020. Data Sharing. In: Schintler L., McNeely C. (eds) Encyclopedia of Big Data. Springer, Cham, Switzerland. 3pp. [[download pdf]](/files/papers/Wen_2020_Data_Sharing.pdf){target="_blank"}
* **Wen, T.**, 2020. Data Aggregation. In: Schintler L., McNeely C. (eds) Encyclopedia of Big Data. Springer, Cham, Switzerland. 4pp. [[download pdf]](/files/papers/Wen_2020_Data_Aggregation.pdf){target="_blank"}

## Reports and Theses

* **Wen, T.**, 2017. _Development of Noble Gas Techniques to Fingerprint Shale Gas and to Trace Sources of Hydrocarbons in Groundwater_ (Doctoral dissertation, University of Michigan). [[download pdf]](/files/papers/Wen_2017_Doctoral_Dissertation.pdf){target="_blank"}

* Nicot, JP., et al., 2015. _Understanding and Managing Environmental Roadblocks to Shale Gas Development: An Analysis of Shallow Gas, NORM, and Trace Metals_ (Technical Report, http://www.rpsea.org/projects/11122-56/).

* **Wen, T.**, 2014. _Constraining groundwater flow in the Glacial Drift and Saginaw Aquifers in the Michigan Basin through helium concentrations and isotopic ratios_ (Master thesis, University of Michigan).

* **Wen, T.**, 201* _Analysis on nitrogen species and isotopic composition of the ornithogenic sediments from Cape Bird, Ross Island, East Antarctica_ (Bachelor thesis, University of Science and Technology of China).

## Preprints and Postprints

* Agarwal, A., **Wen, T.**, Chen, A., Zhang, A.Y., Niu, X., Zhan, X., Xue, L., Brantley, S.L., 2020. Assessing Contamination of Stream Networks Near Shale Gas Development Using a New Geospatial Tool. EarthArXiv. https://doi.org/10.31223/osf.io/qka7d. [[download pdf]](/files/papers/Agarwal_Wen_2020_EarthArXiv.pdf){target="_blank"}

* Woda, J., **Wen, T.**, Lemon, J., Marcon, V., Keeports, C.M., Zelt, F., Steffy, L.Y. and Brantley, S.L., 2020. Methane concentrations in streams reveal gas leak discharges in regions of oil, gas, and coal development. EarthArXiv. https://doi.org/10.31223/osf.io/qka7d. [[download pdf]](/files/papers/Woda_2020_EarthArXiv.pdf){target="_blank"}

* Zheng, G., Liu, M., **Wen, T.**, Wang, H., Yao, H., Brantley, S.L. and Li, Z., 2019. Targeted Source Detection for Environmental Data. arXiv preprint arXiv:1908.11056. [[download pdf]](/files/papers/Zheng_2019_arXiv.pdf){target="_blank"}

## Open Access Datasets

* **Wen, T.**, Woda, J., Marcon, V., Gonzales, M., Niu, X., Herman, A., Guarnieri, M., Li, Z., Brantley, S.L., 2019. Shale Network – Statewide Groundwater in Pennsylvania as of January 2019, Data Commons, Penn State University. [https://doi.org/10.26208/8ag3-b743](https://doi.org/10.26208/8ag3-b743){target="_blank"}.

* **Wen, T.**, Gonzales, M., Niu, X., Herman, A., Guarnieri, M., Li, Z., Brantley, S.L., 2018. Shale Network – Mercer County Groundwater as of August 2018, Data Commons, Penn State University. [https://doi.org/10.18113/D3967X](https://doi.org/10.18113/D3967X){target="_blank"}.

* **Wen, T.**, Woda, J., Gonzales, M., Herman, A., Brantley, S.L., 2018. Shale Network – Lycoming County Groundwater as of October 2018, Data Commons, Penn State University. [https://doi.org/10.18113/D35M2X](https://doi.org/10.18113/D35M2X){target="_blank"}.

* **Wen, T.**, Gonzales, M., Niu, X., Herman, A., Guarnieri, M., Li, Z., Brantley, S.L., 2018. Shale Network – Bradford County Groundwater as of May 2018, Data Commons, Penn State University. [https://doi.org/10.26208/rj0h-qf52](https://doi.org/10.26208/rj0h-qf52){target="_blank"}.

## Online Educational Modules for College Teaching Posted through Carleton College

* **Wen, T.**, Brazil, L., Brantley, S. L., Pelepko, S. and Beattie, S., 2018. Bromide in the Allegheny River System. [https://serc.carleton.edu/hydromodules/steps/191853.html](https://serc.carleton.edu/hydromodules/steps/191853.html){target="_blank"}

* **Wen, T.**, Brazil, L., Brantley, S. L., Pelepko, S. and Beattie, S., 2018. Earthquakes in Pennsylvania. [https://serc.carleton.edu/hydromodules/steps/191859.html](https://serc.carleton.edu/hydromodules/steps/191859.html){target="_blank"}

* **Wen, T.**, Brazil, L., Brantley, S. L., Pelepko, S. and Beattie, S., 2018. How Pennsylvania Disposes of Brines Safely. [https://serc.carleton.edu/hydromodules/steps/191889.html](https://serc.carleton.edu/hydromodules/steps/191889.html){target="_blank"}

* **Wen, T.**, Brazil, L., Brantley, S. L., Pelepko, S. and Beattie, S., 2018. Environmental Issues Related to Brine Disposal from Oil and Gas Development in Pennsylvania. [https://serc.carleton.edu/hydromodules/units/191769.html](https://serc.carleton.edu/hydromodules/units/191769.html){target="_blank"}
